import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";

const moduleUrl = new URL("../src/lib/decisionControl.ts", import.meta.url).href;
const run = (expression) => JSON.parse(execFileSync(process.execPath, ["--experimental-strip-types", "--input-type=module", "-e", `import { buildDecisionControlState, decisionControlStatusSummary, formatDecisionTruth } from ${JSON.stringify(moduleUrl)}; console.log(${expression})`], { encoding: "utf8" }));
const artifact = (kind, overrides = {}) => ({ id: kind, kind, source: "etsy", authority: "primary", fileName: `${kind}.csv`, mimeType: "text/csv", uploadedAt: "2026-08-20T00:00:00Z", periodStart: "2026-07-01", periodEnd: "2026-07-12", targetType: kind === "shop-stats" ? "shop" : "listing", targetId: kind === "shop-stats" ? "shop" : "L1", ownerConfirmed: true, ocrStatus: "not-needed", rows: 1, headers: ["Views"], metrics: [{ label: "Views", value: 0, status: "confirmed-zero" }], ...overrides });
const base = `[${JSON.stringify(artifact("shop-stats"))},${JSON.stringify(artifact("listing-performance"))},${JSON.stringify(artifact("traffic-sources"))}]`;
const listing = JSON.stringify({ id: "L1", title: "測試清單 🧪", protected: false });
const period = JSON.stringify({ start: "2026-07-01", end: "2026-07-12" });
const cases = {
  schema: () => { const result = run(`JSON.stringify(buildDecisionControlState(${base}, ${listing}, ${period}))`); assert.deepEqual(Object.keys(result).sort(), ["blockers", "comparablePeriod", "nextAction", "selectedListing", "status", "truth"].sort()); assert.deepEqual(Object.keys(result.truth).sort(), ["listing-performance", "shop-stats", "traffic-sources"].sort()); assert.equal(result.nextAction.kind, "report-only"); },
  "truth-matrix": () => { for (const truth of ["missing", "invalid", "ocr-unreadable", "period-mismatch", "target-mismatch", "owner-unconfirmed"]) { const overrides = truth === "invalid" ? { metrics: [{ label: "Views", value: null, status: "invalid" }] } : truth === "ocr-unreadable" ? { ocrStatus: "unreadable" } : truth === "period-mismatch" ? { periodStart: "2026-06-01" } : truth === "target-mismatch" ? { targetId: "OTHER", targetType: "listing" } : truth === "owner-unconfirmed" ? { ownerConfirmed: false } : {}; const artifacts = truth === "missing" ? [] : [artifact("shop-stats", overrides), artifact("listing-performance"), artifact("traffic-sources")]; const result = run(`JSON.stringify(buildDecisionControlState(${JSON.stringify(artifacts)}, ${listing}, ${period}))`); assert.equal(result.status, "blocked"); assert.equal(result.truth["shop-stats"], truth); assert.equal(result.blockers[0].truth, truth); } const zero = run(`JSON.stringify(buildDecisionControlState(${base}, ${listing}, ${period}))`); assert.equal(zero.status, "decision-ready"); assert.equal(zero.truth["shop-stats"], "confirmed-zero"); assert.ok(!zero.blockers.length); },
  "truth-recompute": () => { const changed = JSON.parse(base); changed[1].metrics = [{ label: "Views", value: null, status: "invalid" }]; const result = run(`JSON.stringify(buildDecisionControlState(${JSON.stringify(changed)}, ${listing}, ${period}))`); assert.equal(result.status, "blocked"); assert.equal(result.truth["listing-performance"], "invalid"); const repaired = JSON.parse(JSON.stringify(changed)); repaired[1].metrics = [{ label: "Views", value: 4, status: "confirmed" }]; const repairedResult = run(`JSON.stringify(buildDecisionControlState(${JSON.stringify(repaired)}, ${listing}, ${period}))`); assert.equal(repairedResult.status, "decision-ready"); assert.equal(repairedResult.truth["listing-performance"], "confirmed"); },
  "item-isolation": () => { const result = run(`JSON.stringify(buildDecisionControlState(${base}, ${JSON.stringify({ id: "OTHER", title: "Other", protected: false })}, ${period}))`); assert.equal(result.blockers[0].truth, "target-mismatch"); const wrongShop = JSON.parse(base); wrongShop[0].targetId = "OTHER_SHOP"; const wrongShopResult = run(`JSON.stringify(buildDecisionControlState(${JSON.stringify(wrongShop)}, ${listing}, ${period}))`); assert.equal(wrongShopResult.truth["shop-stats"], "target-mismatch"); },
  "shared-state-wiring": () => { const source = readFileSync(new URL("../src/components/EtsyOperationsHub.tsx", import.meta.url), "utf8"); const card = readFileSync(new URL("../src/components/SellerDecisionCard.tsx", import.meta.url), "utf8"); const summary = readFileSync(new URL("../src/components/DecisionControlSummary.tsx", import.meta.url), "utf8"); assert.ok(source.includes("buildDecisionControlState")); assert.ok(source.includes("<DecisionControlSummary control={decisionControl} compact />")); assert.ok(source.includes("control={decisionControl}")); assert.ok(card.includes("<DecisionControlSummary control={control} />")); assert.ok(summary.includes("control.blockers")); assert.ok(summary.includes("control.nextAction.detail")); assert.ok(summary.includes("Truth by evidence lane")); assert.ok(summary.includes("Next action · local / report-only")); assert.ok(summary.includes("DECISION_CONTROL_TRUTH_KEY")); },
  "clarity-copy": () => { const copy = run(`JSON.stringify({ blocked: decisionControlStatusSummary(buildDecisionControlState([], ${listing}, ${period})), missing: formatDecisionTruth("missing"), invalid: formatDecisionTruth("invalid"), zero: formatDecisionTruth("confirmed-zero"), ocr: formatDecisionTruth("ocr-unreadable"), owner: formatDecisionTruth("owner-unconfirmed"), target: formatDecisionTruth("target-mismatch"), period: formatDecisionTruth("period-mismatch"), ready: decisionControlStatusSummary(buildDecisionControlState(${base}, ${listing}, ${period})) })`); assert.match(copy.blocked, /Blocked because/); assert.match(copy.missing, /no usable record/); assert.match(copy.invalid, /unusable/); assert.match(copy.zero, /valid 0, not missing/); assert.match(copy.ocr, /visual review only/); assert.match(copy.owner, /owner confirmation/); assert.match(copy.target, /another listing or shop/); assert.match(copy.period, /outside the selected dates/); assert.match(copy.ready, /confirmed zero remains valid/); },
  "no-live-side-effects": () => { const source = readFileSync(new URL("../src/lib/decisionControl.ts", import.meta.url), "utf8"); assert.ok(source.includes('kind: "report-only"')); assert.ok(!/fetch\(|publish|etsy\/api/i.test(source)); },
  "utf8-canary": () => { const result = run(`JSON.stringify(buildDecisionControlState(${base}, ${listing}, ${period}))`); assert.equal(result.selectedListing.title, "測試清單 🧪"); },
};
const selected = process.argv.find((arg) => arg.startsWith("--case="))?.slice(7);
if (selected) await cases[selected](); else for (const test of Object.values(cases)) await test();
console.log(`decision-control ${selected ?? "all"}: ok`);
